//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DIS.DataServices.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbcOverzicht
    {
        public System.DateTime Jaar { get; set; }
        public int SpecialismeCode { get; set; }
        public int PatientenPerSpecialisme { get; set; }
        public int SubtrajectenPerSpecialisme { get; set; }
        public string DiagnoseCode { get; set; }
        public int PatientenPerDiagnose { get; set; }
        public int SubtrajectenPerDiagnose { get; set; }
        public int ZorgproductCode { get; set; }
        public int PatientenPerZorgproduct { get; set; }
        public int SubtrajectenPerZorgproduct { get; set; }
        public Nullable<decimal> Verkoopprijs { get; set; }
        public System.DateTime Peildatum { get; set; }
        public Nullable<System.DateTime> Bestandsdatum { get; set; }
        public string Versie { get; set; }
    
        public virtual Diagnose Diagnose { get; set; }
        public virtual Specialisme Specialisme { get; set; }
        public virtual Zorgproduct Zorgproduct { get; set; }
    }
}
