//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DIS.DataServices.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbcProfiel
    {
        public System.DateTime Jaar { get; set; }
        public int SpecialismeCode { get; set; }
        public string DiagnoseCode { get; set; }
        public int ZorgproductCode { get; set; }
        public int Patienten { get; set; }
        public int Subtrajecten { get; set; }
        public string ZorgactiviteitCode { get; set; }
        public int Zorgactiviteiten { get; set; }
        public System.DateTime Peildatum { get; set; }
        public Nullable<System.DateTime> Bestandsdatum { get; set; }
        public string Versie { get; set; }
    
        public virtual Diagnose Diagnose { get; set; }
        public virtual Specialisme Specialisme { get; set; }
        public virtual Zorgactiviteit Zorgactiviteit { get; set; }
        public virtual Zorgproduct Zorgproduct { get; set; }
    }
}
